### ISSUE TITLE
wantedlist

### ISSUE THREAD

**Issue by Isoterik** [Isoterik/aHouse#19]
http://fs2.directupload.net/images/150116/h5qi4rot.jpg
mal nur die id, dann id und vergehen, dann nur das vergehen.

**Comment by Isoterik** [comment]
nach wie vor buggy, der erste eintrag wir mit dem Vergehen eingetragen, alle weiteren nur die id.

**Comment by Isoterik** [comment]
die ingame wantedlist bleibt leer

**Comment by codepreller** [comment]
bitte gleich die fehlermeldung immer mit dazu.

**Comment by Isoterik** [comment]
22:38:17 Error in expression <_crime} count _crimes,_crimeName];
};
} foreach _crimes;

ctrlSetText[2403,forma>
22:38:17   Error position: <foreach _crimes;

ctrlSetText[2403,forma>
22:38:17   Error Allgemeiner Fehler in Ausdruck
22:38:17 File mpmissions__CUR_MP.Altis\core\pmenu\fn_wantedInfo.sqf, line 36
