### ISSUE TITLE
factorio items werden nicht beim spielstart geladen im client

### ISSUE THREAD

**Issue by codepreller** [Isoterik/aHouse#9]
fehler wirkt sich aus in fehlermeldung:

22:59:05   Error position: <_val > 0) then
{
_tInv lbAdd format["[%1>
22:59:05   Error Nicht definierte Variable in Ausdruck: _val
22:59:05 File C:\Users\preller\Documents\Arma 3 - Other Profiles\devel%20op\mpmissions\Altis_Life_RPGfh.Altis\core\factorio\fn_factorioInventoryMenu.sqf, line 35
22:59:05 Error in expression <l = missionNameSpace getVariable _x;

**Comment by codepreller** [comment]
vermute die variablen werden nicht geladen, da sie nur nach dem lesen aus der db initialisiert werden und die server dateien koennen ob den tags "FH" am anfang nicht geladen werden.

**Comment by Isoterik** [comment]
_edit_ ja is immer noch wie im ersten comment

**Comment by Isoterik** [comment]
"------------- Factorio Client Query Request -------------"
2015/01/17,  1:39:13 "QUERY: true"
2015/01/17,  1:39:13 "Time to complete: 0 (in seconds)"
2015/01/17,  1:39:13 "Result: _INVALID_SQL_STMT"

**Comment by Isoterik** [comment]
items werden nun geladen, dass produzieren spuckt noch einen fehler aus:

Error in expression <icleListCfg; _basePrice = (_vehicleList select _vIndex) select 1;
_vehicleInfo =>
Error position: <select _vIndex) select 1;
_vehicleInfo =>
Error Nullteiler
\Altis_Life_RPGfh.Altis\core\shops\fn_vehicleShopLBChange.sqf, line 18
